## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("/Users/crkaide/OneDrive - IL State University/Vanderbilt/Vanderbilt/Assignments/6_APIs_and_Weather_Data/World_Weather_Analysis/Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Paamiut,GL,2021-04-20 04:26:15,61.9940,-49.6678,29.70,85,100,6.26,[{'description': 'overcast clouds'}]
1,1,Castro,BR,2021-04-20 04:22:19,-24.7911,-50.0119,52.43,98,4,3.87,[{'description': 'clear sky'}]
2,2,Hofn,IS,2021-04-20 04:24:34,64.2539,-15.2082,34.61,54,22,16.31,[{'description': 'few clouds'}]
3,3,Rolla,US,2021-04-20 04:26:17,37.9514,-91.7713,42.80,70,1,13.80,[{'description': 'clear sky'}]
4,4,Chernyshevskiy,RU,2021-04-20 04:24:50,63.0128,112.4714,23.99,75,100,14.79,[{'description': 'overcast clouds'}]

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
5,5,Kapaa,US,2021-04-20 04:26:19,22.0752,-159.3190,77.00,73,90,6.91,[{'description': 'overcast clouds'}]
9,9,Srandakan,ID,2021-04-20 04:26:22,-7.9386,110.2506,86.23,57,80,11.43,[{'description': 'broken clouds'}]
10,10,Puerto Ayora,EC,2021-04-20 04:22:17,-0.7393,-90.3518,75.99,97,38,5.97,[{'description': 'scattered clouds'}]
15,15,Poum,NC,2021-04-20 04:24:13,-20.2333,164.0167,79.25,79,7,19.24,[{'description': 'clear sky'}]
18,18,Butaritari,KI,2021-04-20 04:22:29,3.0707,172.7902,81.90,79,97,10.13,[{'description': 'moderate rain'}]
19,19,Souillac,MU,2021-04-20 04:20:07,-20.5167,57.5167,78.80,89,40,3.44,[{'description': 'scattered clouds'}]
20,20,Faanui,PF,2021-04-20 04:21:45,-16.4833,-151.7500,82.80,72,10,13.78,[{'description': 'light rain'}]
23,23,Corn Island,NI,2021-04-20 04:26:34,12.1694,-83.0418,80.83,81,98,13.56,[{'description': 'overcast clouds'}]
24,24,Saint-Philippe,RE,2021-04-20 04:19:30,-21.3585,55.7679,77.00,83,80,4.61,[{'description': 'light rain'}]
27,27,Hambantota,LK,2021-04-20 04:24:01,6.1241,81.1185,87.80,79,40,9.22,[{'description': 'scattered clouds'}]

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                2
Date                   0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
5,5,Kapaa,US,2021-04-20 04:26:19,22.0752,-159.3190,77.00,73,90,6.91,[{'description': 'overcast clouds'}]
9,9,Srandakan,ID,2021-04-20 04:26:22,-7.9386,110.2506,86.23,57,80,11.43,[{'description': 'broken clouds'}]
10,10,Puerto Ayora,EC,2021-04-20 04:22:17,-0.7393,-90.3518,75.99,97,38,5.97,[{'description': 'scattered clouds'}]
15,15,Poum,NC,2021-04-20 04:24:13,-20.2333,164.0167,79.25,79,7,19.24,[{'description': 'clear sky'}]
18,18,Butaritari,KI,2021-04-20 04:22:29,3.0707,172.7902,81.90,79,97,10.13,[{'description': 'moderate rain'}]
...,...,...,...,...,...,...,...,...,...,...,...
686,686,Hobyo,SO,2021-04-20 04:23:47,5.3505,48.5268,82.56,72,98,8.81,[{'description': 'moderate rain'}]
688,688,Bartica,GY,2021-04-20 04:29:01,6.4000,-58.6167,75.20,94,0,4.61,[{'description': 'clear sky'}]
690,690,Boffa,GN,2021-04-20 04:29:02,10.1667,-14.0333,77.38,83,37,2.80,[{'description': 'scattered clouds'}]
693,693,Marsh Harbour,BS,2021-04-20 04:24:36,26.5412,-77.0636,78.40,80,56,5.99,[{'description': 'broken clouds'}]
696,696,Sinnamary,GF,2021-04-20 04:29:03,5.3833,-52.9500,75.47,90,100,7.61,[{'description': 'light rain'}]

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Kapaa,US,77.00,[{'description': 'overcast clouds'}],22.0752,-159.3190,
9,Srandakan,ID,86.23,[{'description': 'broken clouds'}],-7.9386,110.2506,
10,Puerto Ayora,EC,75.99,[{'description': 'scattered clouds'}],-0.7393,-90.3518,
15,Poum,NC,79.25,[{'description': 'clear sky'}],-20.2333,164.0167,
18,Butaritari,KI,81.90,[{'description': 'moderate rain'}],3.0707,172.7902,
19,Souillac,MU,78.80,[{'description': 'scattered clouds'}],-20.5167,57.5167,
20,Faanui,PF,82.80,[{'description': 'light rain'}],-16.4833,-151.7500,
23,Corn Island,NI,80.83,[{'description': 'overcast clouds'}],12.1694,-83.0418,
24,Saint-Philippe,RE,77.00,[{'description': 'light rain'}],-21.3585,55.7679,
27,Hambantota,LK,87.80,[{'description': 'scattered clouds'}],6.1241,81.1185,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame

    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"    

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [9]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Kapaa,US,77.00,[{'description': 'overcast clouds'}],22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
9,Srandakan,ID,86.23,[{'description': 'broken clouds'}],-7.9386,110.2506,Puri Brata
10,Puerto Ayora,EC,75.99,[{'description': 'scattered clouds'}],-0.7393,-90.3518,Finch Bay Galapagos Hotel
15,Poum,NC,79.25,[{'description': 'clear sky'}],-20.2333,164.0167,Gîte kajeon
18,Butaritari,KI,81.90,[{'description': 'moderate rain'}],3.0707,172.7902,Isles Sunset Lodge
...,...,...,...,...,...,...,...
686,Hobyo,SO,82.56,[{'description': 'moderate rain'}],5.3505,48.5268,Halane Hotel and Restaurent
688,Bartica,GY,75.20,[{'description': 'clear sky'}],6.4000,-58.6167,Relax Inn Hotel
690,Boffa,GN,77.38,[{'description': 'scattered clouds'}],10.1667,-14.0333,Hôtel Niara Belly
693,Marsh Harbour,BS,78.40,[{'description': 'broken clouds'}],26.5412,-77.0636,Abaco Beach Resort
696,Sinnamary,GF,75.47,[{'description': 'light rain'}],5.3833,-52.9500,ALETHEIA Appartement Sinnamary

In [10]:
hotel_df.count()

City                   217
Country                217
Max Temp               217
Current Description    217
Lat                    217
Lng                    217
Hotel Name             217
dtype: int64

In [11]:
# 7. Drop the rows where there is no Hotel Name.

clean_hotel_df_working = hotel_df.dropna()
clean_hotel_df_working

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Kapaa,US,77.00,[{'description': 'overcast clouds'}],22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
9,Srandakan,ID,86.23,[{'description': 'broken clouds'}],-7.9386,110.2506,Puri Brata
10,Puerto Ayora,EC,75.99,[{'description': 'scattered clouds'}],-0.7393,-90.3518,Finch Bay Galapagos Hotel
15,Poum,NC,79.25,[{'description': 'clear sky'}],-20.2333,164.0167,Gîte kajeon
18,Butaritari,KI,81.90,[{'description': 'moderate rain'}],3.0707,172.7902,Isles Sunset Lodge
...,...,...,...,...,...,...,...
686,Hobyo,SO,82.56,[{'description': 'moderate rain'}],5.3505,48.5268,Halane Hotel and Restaurent
688,Bartica,GY,75.20,[{'description': 'clear sky'}],6.4000,-58.6167,Relax Inn Hotel
690,Boffa,GN,77.38,[{'description': 'scattered clouds'}],10.1667,-14.0333,Hôtel Niara Belly
693,Marsh Harbour,BS,78.40,[{'description': 'broken clouds'}],26.5412,-77.0636,Abaco Beach Resort
696,Sinnamary,GF,75.47,[{'description': 'light rain'}],5.3833,-52.9500,ALETHEIA Appartement Sinnamary

In [12]:
current_to_clean = city_data_df["Current Description"]

In [13]:
current_to_clean

0      [{'description': 'overcast clouds'}]
1            [{'description': 'clear sky'}]
2           [{'description': 'few clouds'}]
3            [{'description': 'clear sky'}]
4      [{'description': 'overcast clouds'}]
                       ...
694         [{'description': 'light snow'}]
695          [{'description': 'clear sky'}]
696         [{'description': 'light rain'}]
697    [{'description': 'overcast clouds'}]
698          [{'description': 'clear sky'}]
Name: Current Description, Length: 699, dtype: object

In [14]:
current_to_clean_new = [i[18:-3] for i in current_to_clean]
current_to_clean_new

['overcast clouds',
 'clear sky',
 'few clouds',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'scattered clouds',
 'clear sky',
 'clear sky',
 'broken clouds',
 'scattered clouds',
 'broken clouds',
 'few clouds',
 'clear sky',
 'overcast clouds',
 'clear sky',
 "light rain'}, {'id': 701, 'main': 'Mist', 'description': 'mist', 'icon': '50n",
 'clear sky',
 'moderate rain',
 'scattered clouds',
 'light rain',
 'scattered clouds',
 'broken clouds',
 'overcast clouds',
 'light rain',
 'clear sky',
 'clear sky',
 'scattered clouds',
 'overcast clouds',
 'broken clouds',
 'broken clouds',
 'scattered clouds',
 'few clouds',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'broken clouds',
 'clear sky',
 'clear sky',
 'few clouds',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'scattered clouds',
 'clear sky',
 'few clouds',
 'few clouds',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'broken clouds',
 'overcast clouds',
 'overcast clouds',
 'broken clouds',
 'overcast clouds',
 'broken clouds',
 'broken clouds',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'light rain',
 'overcast clouds',
 'few clouds',
 'clear sky',
 'clear sky',
 'few clouds',
 'clear sky',
 'clear sky',
 'broken clouds',
 'few clouds',
 'scattered clouds',
 'overcast clouds',
 'scattered clouds',
 'light rain',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'scattered clouds',
 'clear sky',
 'light snow',
 'light rain',
 'few clouds',
 'scattered clouds',
 'overcast clouds',
 'broken clouds',
 'scattered clouds',
 'few clouds',
 "light rain'}, {'id': 741, 'main': 'Fog', 'description': 'fog', 'icon': '50d",
 'few clouds',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'broken clouds',
 'light snow',
 'overcast clouds',
 'broken clouds',
 'clear sky',
 'clear sky',
 'light snow',
 'few clouds',
 'overcast clouds',
 'overcast clouds',
 'broken clouds',
 'overcast clouds',
 'clear sky',
 'broken clouds',
 'clear sky',
 'light rain',
 'clear sky',
 'overcast clouds',
 'few clouds',
 'light rain',
 'scattered clouds',
 'light rain',
 'broken clouds',
 'scattered clouds',
 'overcast clouds',
 'scattered clouds',
 'overcast clouds',
 'clear sky',
 'volcanic ash',
 'clear sky',
 'overcast clouds',
 'light rain',
 'overcast clouds',
 'broken clouds',
 'overcast clouds',
 'scattered clouds',
 'overcast clouds',
 'overcast clouds',
 'few clouds',
 'clear sky',
 "light rain'}, {'id': 701, 'main': 'Mist', 'description': 'mist', 'icon': '50d",
 'overcast clouds',
 'clear sky',
 'scattered clouds',
 'light rain',
 'scattered clouds',
 'broken clouds',
 'overcast clouds',
 'clear sky',
 'scattered clouds',
 'light snow',
 'overcast clouds',
 'clear sky',
 'scattered clouds',
 'scattered clouds',
 'broken clouds',
 'broken clouds',
 'overcast clouds',
 'broken clouds',
 'mist',
 'clear sky',
 'light rain',
 'clear sky',
 'broken clouds',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'broken clouds',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'few clouds',
 'clear sky',
 'broken clouds',
 'broken clouds',
 'broken clouds',
 'overcast clouds',
 'scattered clouds',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'broken clouds',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'light rain',
 'broken clouds',
 'overcast clouds',
 'overcast clouds',
 'heavy intensity rain',
 'few clouds',
 'few clouds',
 'overcast clouds',
 'overcast clouds',
 'scattered clouds',
 'clear sky',
 'scattered clouds',
 'broken clouds',
 'clear sky',
 'scattered clouds',
 'few clouds',
 'few clouds',
 'overcast clouds',
 'broken clouds',
 'few clouds',
 'overcast clouds',
 'clear sky',
 'broken clouds',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 "moderate rain'}, {'id': 301, 'main': 'Drizzle', 'description': 'drizzle', 'icon': '09d",
 'overcast clouds',
 'few clouds',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'few clouds',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'few clouds',
 'overcast clouds',
 'clear sky',
 'scattered clouds',
 'overcast clouds',
 'clear sky',
 'mist',
 'overcast clouds',
 'overcast clouds',
 'broken clouds',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'broken clouds',
 'few clouds',
 'few clouds',
 'haze',
 'light rain',
 'scattered clouds',
 'light snow',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'few clouds',
 'few clouds',
 'clear sky',
 'clear sky',
 'broken clouds',
 'scattered clouds',
 'overcast clouds',
 'scattered clouds',
 'broken clouds',
 'light rain',
 'overcast clouds',
 'scattered clouds',
 'broken clouds',
 'broken clouds',
 'broken clouds',
 'scattered clouds',
 'few clouds',
 'scattered clouds',
 'scattered clouds',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'few clouds',
 'overcast clouds',
 'clear sky',
 'broken clouds',
 'clear sky',
 'moderate rain',
 'overcast clouds',
 'scattered clouds',
 'clear sky',
 'overcast clouds',
 'broken clouds',
 'scattered clouds',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'scattered clouds',
 'light snow',
 'light snow',
 'clear sky',
 'overcast clouds',
 'few clouds',
 'broken clouds',
 'clear sky',
 'clear sky',
 'scattered clouds',
 'clear sky',
 'clear sky',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'broken clouds',
 'broken clouds',
 'scattered clouds',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'few clouds',
 'light rain',
 'overcast clouds',
 'broken clouds',
 'scattered clouds',
 'clear sky',
 'clear sky',
 'broken clouds',
 'scattered clouds',
 'scattered clouds',
 'few clouds',
 'clear sky',
 'light snow',
 'overcast clouds',
 'overcast clouds',
 'few clouds',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'clear sky',
 'few clouds',
 'clear sky',
 'broken clouds',
 'light rain',
 'overcast clouds',
 'scattered clouds',
 'scattered clouds',
 'scattered clouds',
 'broken clouds',
 'scattered clouds',
 'clear sky',
 'clear sky',
 'broken clouds',
 'clear sky',
 'clear sky',
 'light rain',
 'clear sky',
 'clear sky',
 'clear sky',
 'broken clouds',
 'clear sky',
 'overcast clouds',
 'broken clouds',
 'broken clouds',
 'broken clouds',
 'overcast clouds',
 'light rain',
 'clear sky',
 'clear sky',
 'overcast clouds',
 'scattered clouds',
 'clear sky',
 'clear sky',
 'scattered clouds',
 'overcast clouds',
 'few clouds',
 'clear sky',
 'broken clouds',
 'clear sky',
 'broken clouds',
 'light rain',
 'overcast clouds',
 'overcast clouds',
 'scattered clouds',
 'clear sky',
 'light rain',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'broken clouds',
 'overcast clouds',
 'overcast clouds',
 'broken clouds',
 'light rain',
 'light rain',
 'clear sky',
 'moderate rain',
 'clear sky',
 'clear sky',
 'scattered clouds',
 'clear sky',
 'few clouds',
 'scattered clouds',
 'scattered clouds',
 'overcast clouds',
 'few clouds',
 'broken clouds',
 'mist',
 'few clouds',
 'broken clouds',
 'overcast clouds',
 'broken clouds',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'moderate rain',
 'scattered clouds',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'broken clouds',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'few clouds',
 'clear sky',
 'scattered clouds',
 'overcast clouds',
 'few clouds',
 'scattered clouds',
 'scattered clouds',
 'clear sky',
 'few clouds',
 'broken clouds',
 'light rain',
 'moderate rain',
 'clear sky',
 'scattered clouds',
 'light snow',
 'overcast clouds',
 'scattered clouds',
 'clear sky',
 'scattered clouds',
 'few clouds',
 'scattered clouds',
 'overcast clouds',
 'overcast clouds',
 'scattered clouds',
 'overcast clouds',
 'overcast clouds',
 'few clouds',
 'broken clouds',
 'scattered clouds',
 'overcast clouds',
 'scattered clouds',
 'few clouds',
 'scattered clouds',
 'broken clouds',
 'broken clouds',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'broken clouds',
 'overcast clouds',
 'few clouds',
 'overcast clouds',
 'clear sky',
 'broken clouds',
 'scattered clouds',
 'mist',
 'clear sky',
 'haze',
 'broken clouds',
 'clear sky',
 'fog',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'haze',
 'light rain',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'few clouds',
 'clear sky',
 'light rain',
 'clear sky',
 'scattered clouds',
 'light snow',
 'broken clouds',
 'clear sky',
 'clear sky',
 'moderate rain',
 'scattered clouds',
 'broken clouds',
 'overcast clouds',
 'overcast clouds',
 'light rain',
 'scattered clouds',
 'overcast clouds',
 'overcast clouds',
 'few clouds',
 'scattered clouds',
 'fog',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'overcast clouds',
 'broken clouds',
 'scattered clouds',
 'overcast clouds',
 'broken clouds',
 'broken clouds',
 'overcast clouds',
 'clear sky',
 'light snow',
 'broken clouds',
 'light rain',
 'clear sky',
 'clear sky',
 'few clouds',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'scattered clouds',
 'scattered clouds',
 'clear sky',
 'light rain',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'few clouds',
 'overcast clouds',
 'clear sky',
 'scattered clouds',
 'light intensity drizzle',
 'scattered clouds',
 'clear sky',
 'overcast clouds',
 'scattered clouds',
 'overcast clouds',
 'broken clouds',
 'broken clouds',
 'scattered clouds',
 'clear sky',
 'scattered clouds',
 'scattered clouds',
 'overcast clouds',
 'broken clouds',
 'broken clouds',
 'broken clouds',
 'overcast clouds',
 'broken clouds',
 'light snow',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'light rain',
 'broken clouds',
 'overcast clouds',
 'overcast clouds',
 'broken clouds',
 'few clouds',
 'clear sky',
 'scattered clouds',
 'snow',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'few clouds',
 'few clouds',
 'clear sky',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'clear sky',
 'broken clouds',
 'clear sky',
 'overcast clouds',
 'broken clouds',
 'clear sky',
 'overcast clouds',
 'scattered clouds',
 'few clouds',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'scattered clouds',
 'scattered clouds',
 'broken clouds',
 'clear sky',
 'light rain',
 'overcast clouds',
 'heavy intensity rain',
 'overcast clouds',
 'broken clouds',
 'clear sky',
 'light rain',
 'mist',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'broken clouds',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'scattered clouds',
 'overcast clouds',
 'mist',
 'few clouds',
 'overcast clouds',
 'broken clouds',
 'clear sky',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'broken clouds',
 'clear sky',
 'overcast clouds',
 'few clouds',
 'clear sky',
 'light snow',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'light rain',
 'overcast clouds',
 'broken clouds',
 'few clouds',
 'clear sky',
 'few clouds',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'clear sky',
 'scattered clouds',
 'clear sky',
 'clear sky',
 'scattered clouds',
 'scattered clouds',
 'few clouds',
 'clear sky',
 'broken clouds',
 'clear sky',
 'overcast clouds',
 'scattered clouds',
 'clear sky',
 'clear sky',
 'clear sky',
 'overcast clouds',
 'broken clouds',
 'clear sky',
 'scattered clouds',
 'clear sky',
 'few clouds',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'few clouds',
 'clear sky',
 'overcast clouds',
 'overcast clouds',
 'clear sky',
 'overcast clouds',
 'clear sky',
 'scattered clouds',
 'light rain',
 'overcast clouds',
 'moderate rain',
 'few clouds',
 'clear sky',
 'few clouds',
 'scattered clouds',
 'clear sky',
 'broken clouds',
 'broken clouds',
 'light snow',
 'clear sky',
 'light rain',
 'overcast clouds',
 'clear sky']

In [15]:
current_to_clean_new_df = pd.DataFrame(current_to_clean_new)
current_to_clean_new_df.columns = ["Current Description "]
current_to_clean_new_df.columns

Index(['Current Description '], dtype='object')

In [16]:
# MERGE:
# clean_hotel_df_working
# current_to_clean_new_df

clean_hotel_df = clean_hotel_df_working.merge(current_to_clean_new_df, left_index=True, right_index=True)
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name,Current Description
5,Kapaa,US,77.00,[{'description': 'overcast clouds'}],22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach,overcast clouds
9,Srandakan,ID,86.23,[{'description': 'broken clouds'}],-7.9386,110.2506,Puri Brata,broken clouds
10,Puerto Ayora,EC,75.99,[{'description': 'scattered clouds'}],-0.7393,-90.3518,Finch Bay Galapagos Hotel,scattered clouds
15,Poum,NC,79.25,[{'description': 'clear sky'}],-20.2333,164.0167,Gîte kajeon,clear sky
18,Butaritari,KI,81.90,[{'description': 'moderate rain'}],3.0707,172.7902,Isles Sunset Lodge,moderate rain
...,...,...,...,...,...,...,...,...
686,Hobyo,SO,82.56,[{'description': 'moderate rain'}],5.3505,48.5268,Halane Hotel and Restaurent,moderate rain
688,Bartica,GY,75.20,[{'description': 'clear sky'}],6.4000,-58.6167,Relax Inn Hotel,clear sky
690,Boffa,GN,77.38,[{'description': 'scattered clouds'}],10.1667,-14.0333,Hôtel Niara Belly,scattered clouds
693,Marsh Harbour,BS,78.40,[{'description': 'broken clouds'}],26.5412,-77.0636,Abaco Beach Resort,broken clouds
696,Sinnamary,GF,75.47,[{'description': 'light rain'}],5.3833,-52.9500,ALETHEIA Appartement Sinnamary,light rain

In [17]:
del clean_hotel_df["Current Description"]
clean_hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name,Current Description
5,Kapaa,US,77.00,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach,overcast clouds
9,Srandakan,ID,86.23,-7.9386,110.2506,Puri Brata,broken clouds
10,Puerto Ayora,EC,75.99,-0.7393,-90.3518,Finch Bay Galapagos Hotel,scattered clouds
15,Poum,NC,79.25,-20.2333,164.0167,Gîte kajeon,clear sky
18,Butaritari,KI,81.90,3.0707,172.7902,Isles Sunset Lodge,moderate rain
...,...,...,...,...,...,...,...
686,Hobyo,SO,82.56,5.3505,48.5268,Halane Hotel and Restaurent,moderate rain
688,Bartica,GY,75.20,6.4000,-58.6167,Relax Inn Hotel,clear sky
690,Boffa,GN,77.38,10.1667,-14.0333,Hôtel Niara Belly,scattered clouds
693,Marsh Harbour,BS,78.40,26.5412,-77.0636,Abaco Beach Resort,broken clouds
696,Sinnamary,GF,75.47,5.3833,-52.9500,ALETHEIA Appartement Sinnamary,light rain

In [18]:
clean_hotel_df = clean_hotel_df[["City", "Country", "Max Temp", "Current Description ", "Lat", "Lng", "Hotel Name"]]
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Kapaa,US,77.00,overcast clouds,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
9,Srandakan,ID,86.23,broken clouds,-7.9386,110.2506,Puri Brata
10,Puerto Ayora,EC,75.99,scattered clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
15,Poum,NC,79.25,clear sky,-20.2333,164.0167,Gîte kajeon
18,Butaritari,KI,81.90,moderate rain,3.0707,172.7902,Isles Sunset Lodge
...,...,...,...,...,...,...,...
686,Hobyo,SO,82.56,moderate rain,5.3505,48.5268,Halane Hotel and Restaurent
688,Bartica,GY,75.20,clear sky,6.4000,-58.6167,Relax Inn Hotel
690,Boffa,GN,77.38,scattered clouds,10.1667,-14.0333,Hôtel Niara Belly
693,Marsh Harbour,BS,78.40,broken clouds,26.5412,-77.0636,Abaco Beach Resort
696,Sinnamary,GF,75.47,light rain,5.3833,-52.9500,ALETHEIA Appartement Sinnamary

In [20]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [21]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [23]:
# 11a. Add a marker layer for each city to the map. 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))